language:
  php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpunit
